name: Repo check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: python-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          pip install repo

