name: Repo check
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          sudo apt-get update -y
          sudo apt-get install python
          which python
          which pip
          python --version
          python -m pip --version
          pip --version

